version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-name: '@afe1/utils'
    versioning-strategy: increase
